name: check
on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
env:
  project-name: psyke-python
  workflow: check
  test-submodule: psykei/psyke-pytest
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6

      - name: Show Env
        run: | 
          python --version
          pip --version

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history
          submodules: recursive

      - name: Get All Tags
        run: git fetch --tags -f

      - name: Restore Python dependencies
        run: pip install -r requirements.txt

      - name: Create missing predictors
        run: python setup.py create_test_predictors

      - name: Submodule update
        run: |
          pushd test/resources
          git config user.email "bot@noreply.github.com"
          git config user.name "CI bot"
          git remote set-url origin https://x-access-token:${{ secrets.TRIGGER_GITHUB_ACTION }}@github.com/${{ env.test-submodule }}
          (git add predictors/*.onnx && git add tests/*.csv && git add datasets/*.csv) || echo 'nothing to add'
          (git commit -m 'predictors update from workflows' && git push) || echo 'nothing to commit'

      - name: Test
        run: python -m unittest