name: quick-check
on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
env:
  # jdk-version: openjdk@~1.15.0
  project-name: psyke-python
  workflow: quick-check
  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  # gradle-options: "--no-daemon --console=plain --stacktrace"
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Show Env
        run: | 
          python --version
          pip --version

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6

      # - name: Get All Tags
      #   run: git fetch --tags -f

      - name: Restore Python dependencies
        run: pip install -r requirements.txt

      - name: Create missing predictors
        run: python create_missing_predictors.py

      - name: Trigger pytest
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: psykei
          repo: psykei/psyke-pytest
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          propagate_failure: false
          workflow_file_name: update-predictors.yml

      - name: Test
        run: python -m unittest

      - name: Delete predictors
        run: python delete_predictors.py