name: quick-check
on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
env:
  # jdk-version: openjdk@~1.15.0
  project-name: psyke-python
  workflow: quick-check
  # gradle-options: "--no-daemon --console=plain --stacktrace"
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Show Env
        run: | 
          python --version
          pip --version

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6

      # - name: Get All Tags
      #   run: git fetch --tags -f

      - name: Restore Python dependencies
        run: pip install -r requirements.txt

      - name: Change default logging level
        run: sed -i -e 's/DEBUG/WARN/g' psyke/__init__.py

      # - name: Import submodule pytest
      #  run: git submodule add https://github.com/psykei/pytest.git

      - name: Create missing predictors
        run: python create_missing_predictors.py

      - name: Submodule update
        run: |
          pushd test/resources
          git config user.email "matteo.magnini@studio.unibo.it"
          git config user.name "MatteoMagnini"
          git add -f predictors/*.onnx
          git add -f tests/*.csv
          git add -f datasets/*.csv
          (git commit -m 'predictors update from workflows' && git push) || echo 'nothing to commit'

      - name: Test
        run: python -m unittest